version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: m1-vault
    ports:
      - "80:8000"
    env_file:
      - .env
    restart: unless-stopped